### ISSUE TITLE
http://www.rytenlab.com/browser/app/vizER link is not working!

### ISSUE THREAD

**Issue by mmkim1210** [dzhang32/ER_paper_2020_supp_code#1]

**Comment by dzhang32** [comment]
Hi, 

Apologies for the delay, I have only just seen this issue. 

The URL http://www.rytenlab.com/browser/app/vizER is currently live and working for me. There may have been some occasional downtime when we update/configure the site, which may have overlapped with when you tried it. 

I will close this issue for now, but please let me know if you are still running into trouble. 

Thanks, 

David
